import json

output_file = "./LLaMA-Factory/data/ai_text_detect.json"
input_file = "./data/result.jsonl"


result = []
instruction = "Below is a query and its corresponding answer. Please determine if the answer was generated by a human or by a language model. Output 1 for the former and 0 for the latter."
input_text = "\nQuery:{query}\nAnswer:{answer}\nPlease output only '1' or '0', regardless of the language of the query and answer. DO NOT say any additional words or explain."
with open(input_file, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        line = json.loads(line)
        print(line)
        result.append(
            {
                "instruction": instruction,
                "input": input_text.format(
                    query=line["query"], answer=line["human_answer"]
                ),
                "output": "The category is 1",
            }
        )
        result.append(
            {
                "instruction": instruction,
                "input": input_text.format(
                    query=line["query"], answer=line["llm_answer"]
                ),
                "output": "The category is 0",
            }
        )
with open(output_file, "w", encoding="utf-8") as w:
    json.dump(result, w, ensure_ascii=False, indent=4)
